### ISSUE TITLE
compile error ,may be need androidX

### ISSUE THREAD

**Issue by welldone217** [hui-z/flutter_install_plugin#10]
* Error running Gradle:
ProcessException: Process "D:\codes\kcytxl\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details

> Configure project :app
WARNING: API 'variant.getMergeAssets()' is obsolete and has been replaced with 'variant.getMergeAssetsProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeAssets(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
WARNING: API 'variantOutput.getProcessResources()' is obsolete and has been replaced with 'variantOutput.getProcessResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variantOutput.getProcessResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.

> Configure project :install_plugin
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
         *********************************************************
WARNING: This version of device_info will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':install_plugin' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 7s
  Command: D:\codes\kcytxl\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by akindone** [comment]
We are going to upgrade the kotlin-gradle-plugin this weekend. Thanks for reporting this.

**Comment by wuyugege** [comment]
> We are going to upgrade the kotlin-gradle-plugin this weekend. Thanks for reporting this.
i encounterd the same error，the package on pub.dartlang.com didn't upgrade ,please upgrade to support Kotlin Gradle plugin version 1.3.0 and higher,

**Comment by hyjfine** [comment]
we should fix it ASAP @wuyugege @welldone217

**Comment by welldone217** [comment]
thanks a lot,I will try.

**Comment by wuyugege** [comment]
@akindone can you update the package on the  pub.dartlang.com ?

**Comment by hyjfine** [comment]
uploaded!, wait a moment please.
