### ISSUE TITLE
android:authorities

### ISSUE THREAD

**Issue by HowardJJ** [hui-z/flutter_install_plugin#15]
Error:
	Attribute provider#androidx.core.content.FileProvider@authorities value=(com.hjj.amuse.fileProvider) from [:install_plugin] AndroidManifest.xml:12:13-64
	is also present at [com.sangcomz:FishBun:0.9.0] AndroidManifest.xml:14:13-60 value=(com.hjj.amuse.provider).
	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:10:9-18:20 to override.

**Comment by hyjfine** [comment]
fixed at 2.0.1

**Comment by epenli** [comment]
并没有修复 还是有这个问题
