### ISSUE TITLE
第三方库冲突

### ISSUE THREAD

**Issue by 403605209** [hui-z/flutter_install_plugin#17]
AndroidMainfest.xml内：
android:authorities="${applicationId}.fileProvider"字段很多人都是照着网络教程写的。
${applicationId}.fileProvider属性重复会造成冲突，
android:resource="@xml/provider_paths"同理
可以改个名字吗，或者我可以去哪里修改插件内的文本

**Comment by hyjfine** [comment]
fix at 2.0.1
