### ISSUE TITLE
wrong

### ISSUE THREAD

**Issue by sqixin** [hui-z/flutter_install_plugin#2]
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'install_plugin' is using version 1.2.30.

**Comment by akindone** [comment]
Is this causing build fail or a warning? Did you build with IDE like AndroidStudio, and what's the version of it?

**Comment by zhaoxiaohua125** [comment]
me too,My AndroidStudio version is 3.2.1 @akindone
