### ISSUE TITLE
安装失败：MissingPluginException(No implementation found for method installApk on channel install_plugin)

### ISSUE THREAD

**Issue by read0nly** [hui-z/flutter_install_plugin#20]
安装失败：MissingPluginException(No implementation found for method installApk on channel install_plugin)

 InstallPlugin.installApk(path, 'com.****.app').then((result) {
          print('install apk $result');
        }).catchError((error) {
          print("安装失败：$error");
          CommonUtils.showToast(msg: "安装失败：$error");
        });

**Comment by manburenshenglu** [comment]
你好，你最后是怎么解决的这个问题

**Comment by LucasVaa** [comment]
球球了，我也想知道
