### ISSUE TITLE
Podia ter corrido normalmente. Repentinamente mal relatado

### ISSUE THREAD

**Issue by yuefeng007** [hui-z/flutter_install_plugin#29]
PlatformException(IllegalArgumentException, Couldn't find meta-data for provider with authority com.example.app_update_demo.fileProvider.install, null)

Podia ter corrido normalmente.
Repentinamente mal relatado

**Comment by SukkCoder** [comment]
检查你下你的ApplicationID、包名是不是com.example.app_update_demo
