### ISSUE TITLE
flutter_webview_plugin provider error

### ISSUE THREAD

**Issue by jicg** [hui-z/flutter_install_plugin#32]
![image](https://user-images.githubusercontent.com/6479672/69637115-f599fa00-1092-11ea-974f-d18842742de2.png)

**Comment by manburenshenglu** [comment]
同样的问题。。。。。这楼主不怎么解决issue

**Comment by manburenshenglu** [comment]
我已经自己实现了。。。

**Comment by manburenshenglu** [comment]
请问你是怎么解决的最后
