### ISSUE TITLE
install apk error:Couldn't find meta-data

### ISSUE THREAD

**Issue by suyie001** [hui-z/flutter_install_plugin#35]
install apk error: PlatformException(IllegalArgumentException, Couldn't find meta-data for provider with authority com.suyetech.sy_im.fileProvider.install, null)

**Comment by wenxy** [comment]
the same promble！！

**Comment by WingCH** [comment]
same promble

this PR solved
https://github.com/hui-z/flutter_install_plugin/pull/39

**Comment by wang-zeqi** [comment]
同样的问题！！
