### ISSUE TITLE
install_plugin and permission_handler are the same problems in ios. 

### ISSUE THREAD

**Issue by sqixin** [hui-z/flutter_install_plugin#4]
install_plugin and permission_handler are the same problems in ios. It's all the mistakes reported below. I wonder if I've ever met you before. I don't know much about ios.
error message：
install_plugin` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

**Comment by akindone** [comment]
check your `project.pbxproj` setting for `SWIFT_VERSION`.https://github.com/hui-z/flutter_install_plugin/blob/b52512c5c18a5c1c06c3c8e9a3b3925b23c5047b/example/ios/Runner.xcodeproj/project.pbxproj#L446
