### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 5115191** [hui-z/flutter_install_plugin#49]
`android plugin(24742): installApk /data/user/0/com.example/apk/example.apk  com.example`

`install apk error: PlatformException(IllegalArgumentException, Failed to find configured root that contains /data/data/com.example/apk/example.apk,null,null)`

上下两个路径不一致，是什么原因？

**Comment by tion126** [comment]
activity重启后他的参数就没了  有些机型上会有这个问题  只能自己改改

**Comment by 0x10000** [comment]
小米MIUI12.5出现同样错误

**Comment by 5115191** [comment]
> 小米MIUI12.5出现同样错误

后开用`getExternalStorageDirectory()`解决了，之前用的是`getApplicationDocumentsDirectory()`
