### ISSUE TITLE
在安卓11上使用时 会先调取允许安装未知应用权限 允许后闪退

### ISSUE THREAD

**Issue by yingzhong27** [hui-z/flutter_install_plugin#55]
``` dart
Future<Null> _installApk() async {
    String path = await _apkLocalPath;
    InstallPlugin.installApk(path, 'com.XXXXX.XXXXXX');
    //await OpenFile.open(path + '/' + apkName);
  }
```
安卓11上调用这个方法 先去请求了允许安装未知应用权限 允许后就直接闪退了 请问怎么解决

**Comment by gaoyueban** [comment]
解决了吗？

**Comment by yingzhong27** [comment]
> 解决了吗？
https://github.com/yy1300326388/app_installer/issues/5#issue-976691120
请参照我的这个回答 这个插件解决了

**Comment by yingzhong27** [comment]
> 解决了吗？


https://github.com/yy1300326388/app_installer/issues/5#issue-976691120

参照这个回复 希望能帮助到你
