### ISSUE TITLE
The plugins ` install_plugin ` use a deprecated version of the Android embedding.

### ISSUE THREAD

**Issue by l000in** [hui-z/flutter_install_plugin#58]
flutter 2.5.1
The plugins ` install_plugin` use a deprecated version of the Android embedding.
To avoid unexpected runtime failures, or future build failures, try to see if these plugins support the Android V2 embedding. Otherwise, consider removing them since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding: https://flutter.dev/go/android-plugin-migration.

**Comment by fuyufei123** [comment]
没有后续了吗，同问
