### ISSUE TITLE
Incompatible kotlin gradle plugin version

### ISSUE THREAD

**Issue by wsxyeah** [hui-z/flutter_install_plugin#6]
I use `com.android.tools.build:gradle:3.2.1` from flutter 1.0 template

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'install_plugin' is using version 1.2.30.

**Comment by hyjfine** [comment]
Thanks for reporting, we should upgrade the gradle plugin version ASAP.
