### ISSUE TITLE
I'm experiencing an issue with the Kotlin Gradle Plugin version.

### ISSUE THREAD

**Issue by unicornlox** [hui-z/flutter_install_plugin#64]
the exact error is as stated below:
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':install_plugin_v2' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.32

Thank you in advance for your assistance.

**Comment by Go-oG** [comment]
We've upgraded the version, so you can try the new one!
