### ISSUE TITLE
when run : "flutter build apk " error:  android:attr/lStar not found.

### ISSUE THREAD

**Issue by hzysunrain** [hui-z/flutter_install_plugin#75]
run:
flutter build apk

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':install_plugin:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR:C:\flutter_app_v1\build\install_plugin\intermediates\merged_res\release\values\values.xml:211: AAPT: error: resource android:attr/lStar not found.

flutter doctor
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.24.0, on Microsoft Windows [版本 10.0.19045.4717], locale zh-CN)

**Comment by Emanoel7S** [comment]
I just managed to solve the problem by rolling back the flutter version

**Comment by khaled-0** [comment]
Checkout this issue/solution https://github.com/jayeshpansheriya/flutter_native_contact_picker/issues/17#issuecomment-2291178176

**Comment by hzysunrain** [comment]
Thanks, this problem is solved by this way.
