### ISSUE TITLE
install apk error

### ISSUE THREAD

**Issue by zerohh** [hui-z/flutter_install_plugin#8]
I got this problem：
PlatformException(IllegalArgumentException, Failed to find configured root that contains /data/data/com.guarantees.guarante/app_flutter/Download/app-release-1.0.0.apk, null)

Did I use this wrong?

**Comment by hyjfine** [comment]
Steps to Reproduce or any details?

**Comment by zerohh** [comment]
It's my problem.The path of apk is not existence
