### ISSUE TITLE
Get installation result

### ISSUE THREAD

**Issue by trolik** [hui-z/flutter_install_plugin#9]
Is it possible to get result from this plugin?

If i would write native app, it would not be hard (https://stackoverflow.com/questions/48207547/how-to-get-the-result-of-installation-intent), but what about flutter and this plugin?

Thanks!

**Comment by akindone** [comment]
It is possible to send the result of install async, like provide a Stream for flutter app to listen.
```
StreamController<String> _installResultController = StreamController.broadcast();
Stream<String> get installResult => _installResultController.stream;
Future<dynamic> _handler(MethodCall methodCall) {
  switch (methodCall.method) {
    case 'onInstallResult':
      _installResultController.add(methodCall.arguments);
      break;
```
app can listen the Stream
```
InstallPlugin.installResult.listen((remoteData) {
// using the remote data
}
```
But I have to mention that the return value of the function `installApk` is not stand for the install result
```
static Future<String> installApk(String filePath, String appId) async {}
```
Is that you want or have any idea about this issue?
